default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("MAX_THREADS", 5) %>
  timeout: 5000
  pragmas:
    journal_mode: wal
    synchronous: normal
    temp_store: memory
    mmap_size: 134217728
    cache_size: -20000
    wal_autocheckpoint: 10000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  timeout: 20000
  pragmas:
    journal_mode: wal
    synchronous: "off"
    temp_store: memory
    mmap_size: 134217728
    cache_size: -20000
    wal_autocheckpoint: 0
  database: db/test.sqlite3

production:
  <<: *default
  database: storage/db/production.sqlite3
