name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: spinel-coop/setup-rv@main
        with:
          install-gems: true

      - name: Set up database
        env:
          RAILS_ENV: test
        run: |
          bin/rails db:schema:load

      - name: Run tests
        env:
          RAILS_ENV: test
        run: |
          bin/rails test
